// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"c0-go/token"
)

const (
	NoState    = -1
	NumStates  = 75
	NumSymbols = 84
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'f'
1: 'n'
2: 'l'
3: 'e'
4: 't'
5: 'c'
6: 'o'
7: 'n'
8: 's'
9: 't'
10: 'a'
11: 's'
12: 'w'
13: 'h'
14: 'i'
15: 'l'
16: 'e'
17: 'i'
18: 'f'
19: 'e'
20: 'l'
21: 's'
22: 'e'
23: 'r'
24: 'e'
25: 't'
26: 'u'
27: 'r'
28: 'n'
29: 'b'
30: 'r'
31: 'e'
32: 'a'
33: 'k'
34: 'c'
35: 'o'
36: 'n'
37: 't'
38: 'i'
39: 'n'
40: 'u'
41: 'e'
42: '"'
43: ' '
44: '!'
45: '?'
46: '"'
47: '.'
48: '+'
49: '-'
50: '*'
51: '/'
52: '='
53: '='
54: '-'
55: '!'
56: '='
57: '<'
58: '>'
59: '<'
60: '='
61: '>'
62: '='
63: '('
64: ')'
65: '-'
66: '>'
67: ','
68: ':'
69: ';'
70: '_'
71: '0'
72: '\t'
73: '\n'
74: '\r'
75: ' '
76: '/'
77: '/'
78: '\n'
79: 'A'-'Z'
80: 'a'-'z'
81: '0'-'9'
82: '1'-'9'
83: .
*/
